/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiImportExport from "strapi-import-export/strapi-admin";
import pdfReader from "../../src/plugins/pdf-reader/./dist/admin/index.mjs";
import certificateGenerator from "../../src/plugins/certificate-generator/./dist/admin/index.mjs";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.tsx";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
    "strapi-import-export": strapiImportExport,
    "pdf-reader": pdfReader,
    "certificate-generator": certificateGenerator,
  },
});
